version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - mysql
      - redis
    networks:
      - laravel
    command: >
      sh -c "composer install &&
             php artisan key:generate &&
             php artisan migrate &&
             php-fpm"

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_queue
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php artisan horizon
    depends_on:
      - redis
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit
    container_name: laravel_mailpit
    ports:
      - "8025:8025"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
